port: 8001
host: "192.168.178.21"
repositories:
  - url: https://github.com/user/repo
    path: /home/user/repo
    secret: asl98rr98fh3we2f3lb54iauh
    deploy: git pull && sh build.sh
loggers:
  - name: file
    filename: webhook.log
    timestamp: true